In [3]:
import numpy as np
list_element=[]
n=int(input("Enter square matrix: "))
for row in range(n):
    for col in range(n):
        element = int(input("Enter Matrix element: "))
        list_element.append(element)

matrix=np.array(list_element).reshape(n,n)
print(matrix)
#loop to swap diagonal
for index in range(n):
        temp = matrix[index][index]
        matrix[index][index] = matrix[index][n - index - 1]
        matrix[index][n - index - 1] = temp
print("Swapped Matrix is :")
print(matrix)

Enter square matrix: 4
Enter Matrix element: 1
Enter Matrix element: 2
Enter Matrix element: 3
Enter Matrix element: 4
Enter Matrix element: 5
Enter Matrix element: 6
Enter Matrix element: 7
Enter Matrix element: 8
Enter Matrix element: 9
Enter Matrix element: 10
Enter Matrix element: 11
Enter Matrix element: 12
Enter Matrix element: 13
Enter Matrix element: 14
Enter Matrix element: 15
Enter Matrix element: 16
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Swapped Matrix is :
[[ 4  2  3  1]
 [ 5  7  6  8]
 [ 9 11 10 12]
 [16 14 15 13]]


In [1]:
import numpy as np
size=int(input("Enter size square matrix: "))
n=size*size
list_element=list(int(num) for num in input("Enter list of elements seperated by space: ").strip().split())[:n]
matrix=np.array(list_element).reshape(size,size)
print(matrix)
matrix=np.fliplr(matrix)
print("Swapped Matrix is :")
print(matrix)

Enter size square matrix: 3
Enter list of elements seperated by space: 1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Swapped Matrix is :
[[3 2 1]
 [6 5 4]
 [9 8 7]]
